# Generated by Django 4.1.7 on 2023-03-25 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 19, 30, 29, 498880, tzinfo=datetime.timezone.utc)),
        ),
    ]
