# Generated by Django 4.1.7 on 2023-03-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_choice_question_alter_question_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='polls.question'),
        ),
    ]
