# Generated by Django 4.1.7 on 2023-04-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.CharField(default='11:15 PM', max_length=10),
        ),
    ]
