# Generated by Django 4.1.7 on 2023-04-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_note_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.CharField(default='01/04/23', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.CharField(default='11:21 PM', max_length=10),
        ),
    ]
